#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep  9 19:08:15 2023

@author: tingtingli
"""

import numpy as np
from matplotlib import pyplot as plt
from scipy.interpolate import CubicSpline

#BG Values
bloodSugarB = input("What was your blood sugar at breakfast?")
bloodSugarL = input("What was your blood sugar at lunch?")
bloodSugarD = input("What was your blood sugar at dinner?")

#Correction
normBG = input("What is your standard BG value?")
BGCorrection = input("What is your blood sugar correction value? 1 unit of insulin correction per _____ mg/dL over standard blood sugar value (Fill in the blank)")

#Insulin
insulinB = input("What was your breakfast short acting insulin intake? Enter in units")
insulinL = input("What was your lunch short acting insulin intake? Enter in units")
insulinD = input("What was your dinner short acting insulin intake? Enter in units")

#LongActing
LongActing = input("What is your hourly Long Acting Insulin intake?")
LongActingDay = float(LongActing)*24

#Calculations

#BG
bgB = ((float(bloodSugarB) - float(normBG))/float(BGCorrection))
bgL = ((float(bloodSugarL) - float(normBG))/float(BGCorrection))
bgD = ((float(bloodSugarD) - float(normBG))/float(BGCorrection))

if bgB < 0:
    bgB = 0

if bgL < 0:
    bgL = 0
    
if bgD < 0:
    bgD = 0

totCorrection = float(((float(bloodSugarB) - float(normBG)) + (float(bloodSugarL) - float(normBG)) + (float(bloodSugarD) - float(normBG))/float(BGCorrection)))

#Tot. Insulin
totInsulin = float(insulinB) + float(insulinL) + float(insulinD) + float(totCorrection)

#prices
dailyPrice = (598/15000) * totInsulin 

#month Calculator
days = input("How many days are in the month you'd like to solve for?")
monthlyPrice = (dailyPrice * float(days))

#output
print("Base on your insulin intake for today, " + str(totInsulin) + " your average daily insulin spending is: " + str(dailyPrice) + " and your monthly insulin spending is: " + str(monthlyPrice) + " for this month.")


